<?php

if( function_exists('acf_add_local_field_group') ) {

    // Images
    acf_add_local_field_group(array(
        'key' => 'go-media-renderer-picture-fields',
        'title' => '<picture> element',
        'fields' => array(
            array(
                'key' => 'wp_media_renderer_force_portrait_field',
                'label' => __('Force to display full image', 'go-media-renderer'),
                'name' => 'force_portrait',
                'type' => 'true_false',
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_display_legend_field',
                'label' => __('Display legend if possible', 'go-media-renderer'),
                'name' => 'display_legend',
                'type' => 'true_false',
                'default_value' => 1,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_mob_img',
                'label' => __('Mobile image', 'go-media-renderer'),
                'name' => 'mob_img',
                'type' => 'image',
                'instructions' => __("This image will appear on mobile. Use this field whenever you can’t get an image properly framed on mobile.", 'go-media-renderer'),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'wp_media_renderer_tab_img',
                'label' => __('Tablet image'),
                'name' => 'tab_img',
                'type' => 'image',
                'instructions' => __("This image will appear on tablets. Use this field whenever you can’t get an image properly framed on tablets.", 'go-media-renderer'),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'attachment',
                    'operator' => '==',
                    'value' => 'image',
                ),
                array(
                    'param' => 'attachment',
                    'operator' => '!=',
                    'value' => 'image/svg+xml',
                ),
            ),
        ),

        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
    ));

    // Videos
    acf_add_local_field_group(array(
        'key' => 'go-media-renderer-video-fields',
        'title' => __('Video element', 'go-media-renderer'),
        'fields' => array(
            array(
                'key' => 'wp_media_renderer_vid_fs',
                'label' => __('Is the video fullscreen?', 'go-media-renderer'),
                'name' => 'fs_vid',
                'type' => 'true_false',
                'instructions' => __('If the video is fullscreen (goes from one side of the screen to the other), you must check this option and upload a second video for mobile devices to offer optimal quality and file size on each screen.', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_autoplay',
                'label' => __('Autoplay', 'go-media-renderer'),
                'name' => 'autoplay',
                'type' => 'true_false',
                'instructions' => __('If this option is checked, the video will play without waiting for user interaction.', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_muted',
                'label' => __('Muted', 'go-media-renderer'),
                'name' => 'muted',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_loop',
                'label' => __('Loop', 'go-media-renderer'),
                'name' => 'loop',
                'type' => 'true_false',
                'instructions' => __('The video will play in a loop.', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_controls',
                'label' => __('Controls', 'go-media-renderer'),
                'name' => 'controls',
                'type' => 'true_false',
                'instructions' => __('Displays video controls (play/stop, duration, etc.).', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_controls_fs',
                'label' => __('Fullscreen button', 'go-media-renderer'),
                'name' => 'controls_fs',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_controls_muted',
                'label' => __('Mute button', 'go-media-renderer'),
                'name' => 'controls_muted',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'wp_media_renderer_vid_thumbnail',
                'label' => __('Thumbnail', 'go-media-renderer'),
                'name' => 'thumbnail',
                'type' => 'image',
                'instructions' => __('This image will appear when the video is loading.', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'wp_media_renderer_vid_resp',
                'label' => __('Video to display on mobile', 'go-media-renderer'),
                'name' => 'vid_resp',
                'type' => 'file',
                'instructions' => __('Version of the video that will be displayed on smaller screens.', 'go-media-renderer'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'mime_types' => 'mp4,mov,webm',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'attachment',
                    'operator' => '==',
                    'value' => 'video',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}